### ISSUE TITLE
6.0 Login issue error

### ISSUE THREAD

**Issue by Ofelin** [AionGermany/aion-germany#103]
Hey,

I am getting the following error in LS when trying to connect to 6.0. Any idea? 

(Using JDK 1.8)

Thanks!

```
2:51:08.273 INFO [main]: - AL Login Server started in 1 seconds.
12:51:18.266 INFO [pool-3-thread-2]: - PlayerTransfer perform task init. 0 new tasks.
12:51:42.655 INFO [AcceptReadWrite Dispatcher]: - Connection attemp from: 127.0.0.1
Exception in thread "AcceptReadWrite Dispatcher" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at com.aionemu.loginserver.network.aion.AionServerPacket.write(AionServerPacket.java:51)
        at com.aionemu.loginserver.network.aion.LoginConnection.writeData(LoginConnection.java:168)
        at com.aionemu.commons.network.Dispatcher.write(Dispatcher.java:297)
        at com.aionemu.commons.network.AcceptReadWriteDispatcherImpl.dispatch(AcceptReadWriteDispatcherImpl.java:88)
        at com.aionemu.commons.network.Dispatcher.run(Dispatcher.java:104)

```

**Comment by FrozenKiller35** [comment]
No Changes made on Login Server but did you check if the port's are free (netstat -a) and not used by another app ?
