### ISSUE TITLE
[QuestEngine] Can't initialize quest handlers.

### ISSUE THREAD

**Issue by SayoNarAa** [AionGermany/aion-germany#105]
Hello I do not know too much or postpone the problem so I post it here ^^

I'm having a little trouble with loading quests, if you know where it's coming from?...

`21:54:05.809 WARN [InstantPool-1]: - Exception in a Runnable execution:
com.aionemu.gameserver.GameServerError: [QuestEngine] Can't initialize quest handlers.
        at com.aionemu.gameserver.questEngine.QuestEngine.load(QuestEngine.java:1129) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer$2.run(GameServer.java:258) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.NullPointerException: null
        at com.aionemu.gameserver.questEngine.QuestEngine.load(QuestEngine.java:1123) ~[AL-Game.jar:na]
        ... 6 common frames [omitted`]()

**Comment by Falke3434** [comment]
Give us a little mor Time...we have many work ;)

**Comment by SayoNarAa** [comment]
Yes :) I wish you good luck anyway ^^
