### ISSUE TITLE
Despawn Minion

### ISSUE THREAD

**Issue by Dhannyjsb** [AionGermany/aion-germany#125]
Error when try despawn minion with summon pet button. 

`20:45:46.081 ERROR[PacketProcessor:2]: - Error handling client (kuma) message :[C] 0xDD SB
java.lang.NullPointerException: null
        at com.aionemu.gameserver.services.toypet.MinionService.despawnMinion(Unknown Source) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.network.aion.A.SB.runImpl(Unknown Source) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.network.aion.AionClientPacket.run(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) [al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:41) [al-commons.jar:na]
        at com.aionemu.commons.network.PacketProcessor$PacketProcessorTask.run(PacketProcessor.java:266) [al-commons.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]`

**Comment by FrozenKiller35** [comment]
I added a fix pls test ;)

**Comment by Dhannyjsb** [comment]
fixed :) 👍
