### ISSUE TITLE
Luna Shop Error

### ISSUE THREAD

**Issue by hiderian** [AionGermany/aion-germany#126]
Luna shop doesn't work after completed the Housing quest. I'm not sure the Housing quests are related with luna shop, but when I delete my own house from SQL data, luna shop works.
If I can’t solve the issues, I want to disable the luna shop. The error message show up when I click the luna shop after done the Housing quest so I think it’s better to disable it.

I completed all of [Housing Quest] 18800, 18801, 18802, 18806, 18807, 18827, 18828, 18829, 18830, 18831, 18832, 18847. Then, I lerned the skill "ID: 749247" but I can't use it after re-login to the game because the house data doesn't store in DB.

However, it seems not only Luna and House problem.

![01](https://user-images.githubusercontent.com/46945959/51576159-87c3f580-1ef8-11e9-8b2b-7af1ec483a30.png)
![02](https://user-images.githubusercontent.com/46945959/51576184-9b6f5c00-1ef8-11e9-9b60-6a4c12a48ebe.png)

2019-01-20 08:02:14,641 class com.aionemu.gameserver.GameServer$2 - execution time: 5984msec
2019-01-20 08:02:20,537 class com.aionemu.gameserver.utils.chathandlers.ChatProcessor$1 - execution time: 5889msec
2019-01-20 08:02:22,768 class com.aionemu.gameserver.GameServer$2 - execution time: 14139msec
2019-01-20 08:02:24,890 class com.aionemu.gameserver.GameServer$2 - execution time: 16267msec
2019-01-20 08:02:25,514 Missing zone : 301690000
2019-01-20 08:02:25,545 Missing zone : 301690000
2019-01-20 08:02:25,607 class com.aionemu.gameserver.GameServer$2 - execution time: 16979msec
2019-01-20 08:02:42,385 Automatic restart/shutdown system disable.
2019-01-20 08:08:34,374 Unknown packet received from Aion client: 0x00D9, state=IN_GAME 
0000: 01                                                 .
2019-01-20 08:08:49,510 Exception in a Runnable execution:
java.lang.NullPointerException: null
	at com.aionemu.gameserver.services.player.LunaShopService.onLogout(LunaShopService.java:592) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.player.PlayerLeaveWorldService.startLeaveWorld(PlayerLeaveWorldService.java:219) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.player.PlayerLeaveWorldService$1.run(PlayerLeaveWorldService.java:95) ~[AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by FrozenKiller35** [comment]
They are all on our Todo because a lot was changed with 6.2 but for know the main problem should be
2019-01-20 08:08:34,374 Unknown packet received from Aion client: 0x00D9, state=IN_GAME
0000: 01 .

**Comment by hiderian** [comment]
Yes, I know that the unknown packet error is showing. I changed all of data in l10n folder such as CutScene, Dialogs, Fonts, Help, Housing, Strings and UI in order to change language by unpacking data.pak. It might be why but I just only edited the part of language.

![01](https://user-images.githubusercontent.com/46945959/51647307-8dd0d980-1fbf-11e9-9ef2-36310d5c3a92.png)
This screenshot is inside of enu folder in L10N. These pak files are made myself. Why I don't use data.pak is because if I use data.pak the language will be Korean.

2019-01-20 09:34:57,712 ERROR [PacketProcessor:1] mysql5.MySQL5HousesDAO [MySQL5HousesDAO.java]:165] Could not store studio data. Duplicate entry '2001' for key 'address'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'es2001' for key 'address'

However, the same error has occurred even if I use only 5.8 client. This report is for 5.8. I'm not testing 6.2 yet.

I'm using

**Comment by hiderian** [comment]
The unknown packet error is showing because I changed all of data in l10n folder in order to change language by unpacking data.pak.

2019-01-20 09:34:57,712 ERROR [PacketProcessor:1] mysql5.MySQL5HousesDAO [MySQL5HousesDAO.java]:165] Could not store studio data. Duplicate entry '2001' for key 'address'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'es2001' for key 'address'

However, the same error has occurred even if I use official 5.8 client. This report is for 5.8. I'm not testing 6.2 yet.

**Comment by hiderian** [comment]
The unknown packet error is showing because I changed all of data in l10n folder in order to change language by unpacking data.pak.

2019-01-20 09:34:57,712 ERROR [PacketProcessor:1] mysql5.MySQL5HousesDAO [MySQL5HousesDAO.java]:165] Could not store studio data. Duplicate entry '2001' for key 'address'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'es2001' for key 'address'

However, the same error has occurred even if I use official 5.8 client. This report is for 5.8. I'm not testing 6.2 yet.

**Comment by hiderian** [comment]
I tried to import all of them from 6.0 but nothing has changed.

**Comment by hiderian** [comment]
I've found a bit curious from the console log. This may be a cause.

2019-01-27 11:52:14,997 INFO  [PacketProcessor:0] com.aionemu.gameserver.network.aion.AionClientPacket [AionClientPacket.java:122] [C] 0x114 CM_FIND_GROUP wont be processed cuz its valid state don't match current connection state: AUTHED
2019-01-27 11:52:15,402 INFO  [PacketProcessor:2] com.aionemu.gameserver.network.aion.AionClientPacket [AionClientPacket.java:122] [C] 0x1A6 CM_GET_HOUSE_BIDS wont be processed cuz its valid state don't match current connection state: AUTHED

**Comment by FrozenKiller35** [comment]
@hiderian 
Thats not a problem its ok

**Comment by hiderian** [comment]
Idk the solutions... Anyway, I don’t need the luna shop system for me so I want to disable and/or turn off the luna shop icon like disable the in-game shop icon but is it possible?

**Comment by ryuzaki01** [comment]
I have the fix here 
#151
