### ISSUE TITLE
Housing SQL v5.8

### ISSUE THREAD

**Issue by projectrpgmv** [AionGermany/aion-germany#127]
I'm using "Clean 5.6 DB with all updates 30.06.18" and manual update from folder "update" after 30.06.18..

`10:05:26.054 ERROR[main]: - Could not store studio data. Column 'sign_notice' cannot be null
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'sign_notice' cannot be null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_80]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_80]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_80]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_80]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:138) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5HousesDAO.insertNewHouse(MySQL5HousesDAO.java]:160) [na:na]
        at mysql5.MySQL5HousesDAO.storeHouse(MySQL5HousesDAO.java]:110) [na:na]
        at com.aionemu.gameserver.model.house.House.save(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.services.HousingBidService.addHouseToAuction(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.services.HousingBidService.fillBidData(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.services.HousingBidService.start(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(Unknown Source) [AL-Game.jar:na]
10:05:26.132 ERROR[main]: - Cannot insert house bid
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`al_server_gs`.`house_bids`, CONSTRAINT `house_id_ibfk_1` FOREIGN KEY (`house_id`) REFERENCES `houses` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_80]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_80]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_80]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_80]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:138) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5HouseBidsDAO.addBid(MySQL5HouseBidsDAO.java]:104) ~[na:na]
        at com.aionemu.gameserver.services.HousingBidService.addHouseToAuction(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.services.HousingBidService.fillBidData(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.services.HousingBidService.start(Unknown Source) [AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(Unknown Source) [AL-Game.jar:na]`

**Comment by projectrpgmv** [comment]
fixed. Import housing table from DB 6.0.
