### ISSUE TITLE
gameserver crash

### ISSUE THREAD

**Issue by Sephiroth91** [AionGermany/aion-germany#132]
Hallo,
wenn ich den Gameserver starte bekomme ich folgenden fehler:

2019-02-14 00:40:40,067 ERROR [InstantPool-3] com.aionemu.commons.scripting.impl.javacompiler.ErrorListener [ErrorListener.java:63] Java Compiler ERROR: cannot find symbol
symbol  : class SM_FLAG_INFO
location: package com.aionemu.gameserver.network.aion.serverpackets
Source: /Aion/server/AL-Game/./data/scripts/system/handlers/ai/FlagAI2.java
Line: 24
Column: 57
2019-02-14 00:40:40,424 ERROR [InstantPool-3] com.aionemu.commons.scripting.impl.javacompiler.ErrorListener [ErrorListener.java:63] Java Compiler ERROR: cannot find symbol
symbol: class SM_FLAG_INFO
Source: /Aion/server/AL-Game/./data/scripts/system/handlers/ai/FlagAI2.java
Line: 48
Column: 106

Ich benutze Java 7. Hab ich was falsch gemacht oder funktioniert der gameserver mit 6.0 derzeit nicht?

**Comment by Falke3434** [comment]
Benutze den aktuellen Sourcecode!

**Comment by Sephiroth91** [comment]
Hallo Falke3434,

das Ergebnis ist leider das selbe. Es wird noch das hier ausgegeben:

2019-02-14 13:16:05,937 WARN  [InstantPool-3] com.aionemu.commons.utils.concurrent.ExecuteWrapper [ExecuteWrapper.java:48] Exception in a Runnable execution:
com.aionemu.gameserver.GameServerError: [AIEngine] Can't initialize ai handlers.
	at com.aionemu.gameserver.ai2.AI2Engine.load(Unknown Source) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.GameServer$2.run(Unknown Source) ~[AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:46) ~[al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:39) [al-commons.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_95]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_95]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_95]
Caused by: java.lang.RuntimeException: Error while compiling classes
	at com.aionemu.commons.scripting.impl.javacompiler.ScriptCompilerImpl.doCompilation(ScriptCompilerImpl.java:198) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.impl.javacompiler.ScriptCompilerImpl.compile(ScriptCompilerImpl.java:167) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.impl.ScriptContextImpl.init(ScriptContextImpl.java:147) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.scriptmanager.ScriptManager.load(ScriptManager.java:105) ~[al-commons.jar:na]
	... 7 common frames omitted

**Comment by Falke3434** [comment]
Ich wiederhole: Benutze den aktuellen Sourcecode und compiliere den gameserver neu - ich nutze den doch auch und habe den Fehler nicht (zuletzt getestet vor 2h)

**Comment by Sephiroth91** [comment]
Sehr merkwürdig :/ ich hatte den neusten Sourcecode benutzt und hatte den alten auf dem Server mit dem neuen überschrieben, aber vielleicht lief da was falsch. Ich habe nun nochmal alles gelöscht und von vorne gemacht.
Ich habe alles von hier runtergeladen und mit den batch datein alles compiliert beim Gameserver habe ich die yguard batch genommen. Danach habe ich die compilierten Daten auf einen Ubuntu Server hochgeladen und dort ausgeführt. Loginserver und Chatserver funktionieren ohne Probleme aber beim Gameserver kommt wieder die Fehlermeldung.

**Comment by Falke3434** [comment]
Bitte niemals (nur) überschreiben, denn alles was zb. entfernt wurde bleibt ja dann bei dir bestehen! Und genau das führt dann zu Fehlern

**Comment by FrozenKiller35** [comment]
Probier es mal ohne yguard das wird bei uns schon länger nicht mehr gepflegt und angewendet.

**Comment by Sephiroth91** [comment]
Es lag tatsächlich an yguard. Ich habe die andere Datei für den Gameserver benutzt und nun funktioniert es. Vielen dank für die Hilfe :)
