### ISSUE TITLE
GS Start Error: Siege Boss Issue/Missing

### ISSUE THREAD

**Issue by toysin666** [AionGermany/aion-germany#135]
`Critical Error - Thread: main terminated abnormaly: com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1517
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1517
        at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:221) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.ArtifactSiege.onSiegeStart(ArtifactSiege.java:52) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:82) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:247) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.SiegeService.initSieges(SiegeService.java:192) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(GameServer.java:297) ~[AL-Game.jar:na]`

**Comment by FrozenKiller35** [comment]
Disable Siege System its not Updated to 6.0 yet

**Comment by Falke3434** [comment]
we dont have a Siege with ID 1517 on Aion 6.x

for 5.x check the Duxes in the npc_template
