### ISSUE TITLE
Base flag is null

### ISSUE THREAD

**Issue by steven90005** [AionGermany/aion-germany#141]
Although I am using the version of AION-CORE 4.7.5, but I still hope to solve the problem.
Every time I open the GS, the spawnattacker is normal when attacking the base, like this:

15:39:52.340 INFO [pool-2-thread-4]: - Legat kill ! BOSS: Irigani Warmarshal (231646) in BaseId: 76killed by RACE: ELYOS

But after a while (or a few hours), the base will start to make errors, and all the NPCs in the base will disappear, like this:

16:13:53.700 WARN [pool-2-thread-8]: - Exception in a Runnable execution:
java.lang.NullPointerException: Base:76 flag is null!
        at com.aionemu.gameserver.services.base.Base.spawnAttackers(Unknown Source) ~[AC-Game.jar:na]
        at com.aionemu.gameserver.services.base.Base.chooseAttackersRace(Unknown Source) ~[AC-Game.jar:na]
        at com.aionemu.gameserver.services.base.Base$1.run(Unknown Source) ~[AC-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:46) ~[ac-commons-1.3.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:38) [ac-commons-1.3.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_79]
        at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_79]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_79]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_79]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_79]

Then the base will have the same problem one after another.
Finally, all the bases in the game will become empty.

**Comment by steven90005** [comment]
Although I don't know why there are errors, even if the version is different, I still believe that it is a topic worth discussing, because few people are developing the Aion simulator, so I can only come here for help.
Now I know your answer, thx.
