### ISSUE TITLE
[7.x] Startup broken? Missing static data as listed in to do. How to proceed?

### ISSUE THREAD

**Issue by BankaiNoJutsu** [AionGermany/aion-germany#162]
Hey there,

I would like to help with fixing the static data, as it is listed as being needed. However I cannot find what is needed to do. 

Is there any documentation i have not seen/found? If no, would it be possible to explain to me the structure quickly and the required steps, and i would be glad to try and fix these.

I am mainly interested in understanding this error:
`Error at [line=1257, column=158582645]: Undefined ID "110050021".`

As it does not specify from which file the xml validation fails, i was not able to find where.
However item_armor_templates.xml has a reference, for example, and the static_data.xml in the cache also, as i understand it is being created from the above in the data/item folder, right?

A little help would be appreciated.
Cheers for this wonderful project!
B.

```
15:26:14.026 INFO [main]: - [DataManager] Loaded 52 Cubics entries
15:26:14.026 INFO [main]: - [DataManager] Loaded 68 Transformation entries
15:26:14.026 INFO [main]: - [DataManager] Loaded 10 Revive World Start Point entrys
15:26:14.026 INFO [main]: - [DataManager] Loaded 25 Revive Instance Start Point entrys
15:26:14.026 INFO [main]: - [DataManager] Loaded 18 Item Enchant Chances entrys
15:26:14.089 ERROR[main]: - Error at [line=1257, column=158582645]: Undefined ID "110050021".
15:26:14.089 ERROR[main]: - Critical Error - Thread: main terminated abnormaly: java.lang.Error
java.lang.Error: null
        at com.aionemu.gameserver.dataholders.loadingutils.XmlValidationHandler.handleEvent(XmlValidationHandler.java:41) ~[AL-Game.jar:na]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:690) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.errorUnresolvedIDREF(UnmarshallingContext.java:749) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.reflect.Lister$IDREFS$Pack.run(Lister.java:395) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.runPatchers(UnmarshallingContext.java:793) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.endDocument(UnmarshallingContext.java:580) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.ValidatingUnmarshaller.endDocument(ValidatingUnmarshaller.java:76) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.endDocument(SAXConnector.java:99) ~[na:1.7.0_80]
        at org.apache.xerces.parsers.AbstractSAXParser.endDocument(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLDocumentScannerImpl.endEntity(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLEntityManager.endEntity(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLEntityScanner.load(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLEntityScanner.skipSpaces(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLDocumentScannerImpl$TrailingMiscDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.8.1.jar:na]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203) ~[na:1.7.0_80]
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:175) ~[na:1.7.0_80]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[na:1.7.0_80]
        at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214) ~[na:1.7.0_80]
        at com.aionemu.gameserver.dataholders.loadingutils.XmlDataLoader.loadStaticData(XmlDataLoader.java:77) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.dataholders.DataManager.<init>(DataManager.java:162) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.dataholders.DataManager.<init>(DataManager.java:33) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.dataholders.DataManager$SingletonHolder.<clinit>(DataManager.java:289) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.dataholders.DataManager.getInstance(DataManager.java:154) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.GameServer.main(GameServer.java:228) ~[AL-Game.jar:na]
```

**Comment by Falke3434** [comment]
use newest revision
