### ISSUE TITLE
World DB role creation failed

### ISSUE THREAD

**Issue by xiyouxi66** [AionGermany/aion-germany#190]
First of all, thank you for your contribution. Today I tested your latest updated data. The previous work went well together, but after entering the game, the world DB role creation failed.

22:36:22.550 ERROR[PacketProcessor:2]: - Error saving new player: 104407 aion
java.sql.SQLException: Field 'last_transfer_time' doesn't have a default value
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:138) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5PlayerDAO.saveNewPlayer(MySQL5PlayerDAO.java]:263) ~[na:na]
        at com.aionemu.gameserver.services.player.PlayerService.storeNewPlayer(PlayerService.java:146) [AL-Game.jar:na]
        at com.aionemu.gameserver.network.aion.clientpackets.CM_CREATE_CHARACTER.runImpl(CM_CREATE_CHARACTER.java:405) [AL-Game.jar:na]
        at com.aionemu.gameserver.network.aion.AionClientPacket.run(AionClientPacket.java:65) [AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:46) [al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:39) [al-commons.jar:na]
        at com.aionemu.commons.network.PacketProcessor$PacketProcessorTask.run(PacketProcessor.java:269) [al-commons.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]

**Comment by Wern-rm** [comment]
You do not have the last_transfer_time column in the player table
