### ISSUE TITLE
error GameServerDAO class

### ISSUE THREAD

**Issue by fikrivoxel** [AionGermany/aion-germany#206]
i have error in gameserverdao anything wrong with my config ?

oh ya i have mysql 8 its compatible ?

```
11:30:03.436 INFO [main]: - Loaded 0 DAO implementations.
11:30:03.444 INFO [main]: - ThreadPoolManager: Initialized with 34 scheduler, 16 instant, 0 long running thread(s).
11:30:03.444 INFO [main]: - Initializing Key Generator...
Exception in thread "main" com.aionemu.commons.database.dao.DAONotFoundException: DAO for class GameServersDAO not implemented
        at com.aionemu.commons.database.dao.DAOManager.getDAO(DAOManager.java:116)
        at com.aionemu.loginserver.GameServerTable.getDAO(GameServerTable.java:172)
        at com.aionemu.loginserver.GameServerTable.load(GameServerTable.java:68)
        at com.aionemu.loginserver.LoginServer.main(LoginServer.java:140)
```

**Comment by Wern-rm** [comment]
mysqlUtilsDAO

to change 5 to 8
