### ISSUE TITLE
PlayerEnterWorldService.java error after update

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#24]
2018-06-10 17:09:44,367 Error during enter world 321889
java.lang.NullPointerException: null
	at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:863) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:267) ~[AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) [al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]

**Comment by ghostfur** [comment]
I will look at it now!

**Comment by benas80** [comment]
Thanks. 
This is something with:  skillAnimation  problem
in this line:
for (SkillAnimation skillAnimation : player.getSkillAnimationList().getSkillAnimation()) {

**Comment by ghostfur** [comment]
Thanks i will fix all problems! and push again!

**Comment by FrozenKiller35** [comment]
Fixed
