### ISSUE TITLE
Problen when using 64-bit 5.8 client (EU)

### ISSUE THREAD

**Issue by penguinjoe** [AionGermany/aion-germany#3]
For some odd reason the emu throws this exception when attempting to create a new character. This does not happen for the 
[console.log](https://github.com/AionGermany/aion-germany/files/1759174/console.log)
32-bit client.:

2018-02-26 10:15:43,090 Reading failed for packet [C] 0x153 CM_CREATE_CHARACTER
java.lang.IllegalArgumentException: There is no player class with id -1
	at com.aionemu.gameserver.model.PlayerClass.getPlayerClassById(PlayerClass.java:96) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.clientpackets.CM_CREATE_CHARACTER.readImpl(CM_CREATE_CHARACTER.java:115) ~[AL-Game.jar:na]
	at com.aionemu.commons.network.packet.BaseClientPacket.read(BaseClientPacket.java:98) ~[al-commons.jar:na]
	at com.aionemu.gameserver.network.aion.AionConnection.processData(AionConnection.java:297) [AL-Game.jar:na]
	at com.aionemu.commons.network.Dispatcher.parse(Dispatcher.java:245) [al-commons.jar:na]
	at com.aionemu.commons.network.Dispatcher.read(Dispatcher.java:206) [al-commons.jar:na]
	at com.aionemu.commons.network.AcceptReadWriteDispatcherImpl.dispatch(AcceptReadWriteDispatcherImpl.java:80) [al-commons.jar:na]
	at com.aionemu.commons.network.Dispatcher.run(Dispatcher.java:107) [al-commons.jar:na]

attached is my console log. 
JVM in use is JDK_1.8.0_121
I used this version to compile and run (I use the -noverify JVM parameter to sidestep the Java 8's lack of a splitverifyier). I did not rebuild the commons.jar for these runs.

**Comment by FrozenKiller35** [comment]
Did you try to run Game Server with Java 7 ?

**Comment by penguinjoe** [comment]
Not recently. Early on I tried java 7 and found a lot of problems with the commons jar. I have to stress though that the problem only happens with a 64-bit client. With a 32-bit one, there is no problem at all. Perhaps the 64-bit client adds word alignments in the packet that the java 8 bytecode can't deal with. The CM_CREATE_CHARACTER seems to be the only packet with the problem.
