### ISSUE TITLE
Error during enter world 321172 : java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by Katsshura** [AionGermany/aion-germany#35]
Hello, i'm having a problem when i try to connect with my character to the world, it starts loading and then this exceptions is returned.  Could someone help me?

```
2018-06-12 11:47:59,550 Error during enter world 321172 java.lang.NullPointerException: null
	at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:863) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:267) ~[AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) [al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_80]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
2018-06-12 11:48:00,673 Dispatcher error! java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.aionemu.gameserver.network.aion.serverpackets.SM_ATTACK_STATUS.writeImpl(SM_ATTACK_STATUS.java:142) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionServerPacket.write(AionServerPacket.java:144) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionConnection.writeData(AionConnection.java:321) ~[AL-Game.jar:na]
	at com.aionemu.commons.network.Dispatcher.write(Dispatcher.java:289) ~[al-commons.jar:na]
	at com.aionemu.commons.network.AcceptReadWriteDispatcherImpl.dispatch(AcceptReadWriteDispatcherImpl.java:83) ~[al-commons.jar:na]
	at com.aionemu.commons.network.Dispatcher.run(Dispatcher.java:107) ~[al-commons.jar:na]
```

**Comment by benas80** [comment]
Did You update all files and new database sql's executed?

**Comment by Katsshura** [comment]
@benas80 Yes i updated the database with the sql's, though 2 sql's were giving an error 'All parts of a PRIMARY KEY must be NOT NULL; if you need NULL in a key, use UNIQUE instead', so i changed the sql code to unique.

**Comment by ghostfur** [comment]
I think you dont have the last release? because i think those things are fixed 🔢 ?

**Comment by Katsshura** [comment]
I'll downloaded it two days ago, i'll redownload and try again later. When i finish i'll report here the result

**Comment by Katsshura** [comment]
I've downloaded it two days ago, i'll redownload and try again later. When i finish i'll report here the result

**Comment by FrozenKiller35** [comment]
Pls try this code's:

DROP TABLE IF EXISTS `player_skill_skins`;
CREATE TABLE `player_skill_skins` (
  `player_id` int(11) NOT NULL DEFAULT '0',
  `skin_id` int(11) NOT NULL DEFAULT '0',
  `remaining` bigint(22) DEFAULT '0',
  `active` int(1) DEFAULT '0',
  PRIMARY KEY (`player_id`,`skin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `player_events_window`;
CREATE TABLE `player_events_window` (
  `account_id` int(11) NOT NULL DEFAULT '0',
  `event_id` int(11) NOT NULL DEFAULT '0',
  `last_stamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `elapsed` double(11,0) DEFAULT '0',
  PRIMARY KEY (`account_id`,`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by FrozenKiller35** [comment]
Update your f2paccount table in your MYSQL DB
Drop / Delete the old one and use F2p Update - 25.05.2018.sql

**Comment by Katsshura** [comment]
Thanks @FrozenKiller35 doing this fixed the error when aion tries to get f2account informations. But i'm still getting error: Null Exception when trying to enter in the world. I'll try to download it again and rebuild the database.
