### ISSUE TITLE
Skill Skin Errors

### ISSUE THREAD

**Issue by Falke3434** [AionGermany/aion-germany#59]
I can no Skill Skin Cards learn with Cleric, Elyos!

I can learn only 1 Skill Skin (Templer, Elyos)
All other skill Skins makes a Error and some Skill Skin Cards have no "Action":

`2018-06-16 00:24:45,240 ERROR [PacketProcessor:3] mysql5.MySQL5PlayerTitleListDAO [MySQL5PlayerSkillSkinListDAO.java]:68] Could not store skill skin for player 326057 from DB: Duplicate entry '326057' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '326057' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_51]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:138) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
	at mysql5.MySQL5PlayerSkillSkinListDAO.storeSkillSkins(MySQL5PlayerSkillSkinListDAO.java]:65) ~[na:na]
	at com.aionemu.gameserver.model.skinskill.SkillSkinList.addSkillSkin(SkillSkinList.java:76) [AL-Game.jar:na]
	at com.aionemu.gameserver.model.templates.item.actions.SkillAnimationAction.act(SkillAnimationAction.java:55) [AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM.runImpl(CM_USE_ITEM.java:204) [AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionClientPacket.run(AionClientPacket.java:65) [AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) [al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:41) [al-commons.jar:na]
	at com.aionemu.commons.network.PacketProcessor$PacketProcessorTask.run(PacketProcessor.java:266) [al-commons.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
2018-06-16 00:24:52,498 ERROR [PacketProcessor:1] mysql5.MySQL5PlayerTitleListDAO [MySQL5PlayerSkillSkinListDAO.java]:68] Could not store skill skin for player 326057 from DB: Duplicate entry '326057' for key 'PRIMARY'
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '326057' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_51]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_51]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1199) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:138) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
	at mysql5.MySQL5PlayerSkillSkinListDAO.storeSkillSkins(MySQL5PlayerSkillSkinListDAO.java]:65) ~[na:na]
	at com.aionemu.gameserver.model.skinskill.SkillSkinList.addSkillSkin(SkillSkinList.java:76) [AL-Game.jar:na]
	at com.aionemu.gameserver.model.templates.item.actions.SkillAnimationAction.act(SkillAnimationAction.java:55) [AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM.runImpl(CM_USE_ITEM.java:204) [AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionClientPacket.run(AionClientPacket.java:65) [AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) [al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:41) [al-commons.jar:na]
	at com.aionemu.commons.network.PacketProcessor$PacketProcessorTask.run(PacketProcessor.java:266) [al-commons.jar:na]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_51]
2018-06-16 00:26:02,715 WARN  [PacketProcessor:1] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600149
2018-06-16 00:26:04,292 WARN  [PacketProcessor:0] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600149
2018-06-16 00:26:05,831 WARN  [PacketProcessor:2] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600129
2018-06-16 00:26:06,591 WARN  [PacketProcessor:1] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600129
2018-06-16 00:26:06,966 WARN  [PacketProcessor:3] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600149
2018-06-16 00:26:07,337 WARN  [PacketProcessor:0] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600129
2018-06-16 00:26:07,763 WARN  [PacketProcessor:2] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600149
2018-06-16 00:26:08,057 WARN  [PacketProcessor:1] com.aionemu.gameserver.network.aion.clientpackets.CM_USE_ITEM [CM_USE_ITEM.java:145] CHECKPOINT: No Item use Action: 326057 189600129
`

**Comment by ghostfur** [comment]
Falke do you have the skill card id's from the ones that doesnt work for you? so i can take a look !

**Comment by Falke3434** [comment]
IDs you can see on the end from this logfile ;)

**Comment by ghostfur** [comment]
Ow yeah sorry :) thanks i will check!

**Comment by ghostfur** [comment]
I forgot some hahaha! Sorry

**Comment by ghostfur** [comment]
Fertig ill upload now :)

**Comment by FrozenKiller35** [comment]
@Falke3434 

Probier es nochmal wenn du das hier verwendet hast:

**Comment by FrozenKiller35** [comment]
DROP TABLE IF EXISTS `player_skill_skins`;
CREATE TABLE `player_skill_skins` (
  `player_id` int(11) NOT NULL DEFAULT '0',
  `skin_id` int(11) NOT NULL DEFAULT '0',
  `remaining` bigint(22) DEFAULT '0',
  `active` int(1) DEFAULT '0',
  PRIMARY KEY (`player_id`,`skin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
