### ISSUE TITLE
SERVER has not been able to run smoothly

### ISSUE THREAD

**Issue by zxysm** [AionGermany/aion-germany#61]
Operating environment: WIN10 PRO (1803) + JDK1.8 (game server using JRE1.7) + MariaDB 10 + AION 5.8 CHS client.
After opening the server, open the client to register an account and establish a character to enter the game. It is found that the character does not have any skills (including active and passive). Even if you use the GM command to assign character skills, you enter the game after exiting. The previously assigned skills all disappear. Now. But there are no such problems using several other server-side emulators. I hope to help find the problem and solve it. Thank you very much!
Attachments are screenshots of skills within the game client. Picture 1 is active and picture 2 is passive.
![1](https://user-images.githubusercontent.com/20953114/41498106-7cb5f968-7197-11e8-9a68-99296fb6ed85.jpg)
![2](https://user-images.githubusercontent.com/20953114/41498107-7cf82860-7197-11e8-8921-34b97ae39ed3.jpg)
Game server log is as follows:

18:28:24.988 INFO [ReadWrite-0 Dispatcher]: - Authentication with Client Version 5.8
18:28:25.094 INFO [InstantPool-14]: - [LoginServer] Account authed: 2 = admint
18:28:25.154 INFO [PacketProcessor:3]: - 0 IPv4: {}
18:28:25.155 INFO [PacketProcessor:3]: - Mac: 90-2B-34-37-01-14
18:28:25.155 INFO [PacketProcessor:3]: - HDD SERIAL: 2139D56C
18:28:25.155 INFO [PacketProcessor:3]: - Local IP: {192.168.2.11}
18:28:25.155 INFO [PacketProcessor:3]: - Connect IP: 192.168.2.11
18:29:51.126 ERROR[pool-2-thread-30]: - Could not restore Event Window account: 321038 from DB: Table 'al_ser58_gs.player_events_window' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_events_window' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_25]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5PlayerEventsWindowDAO.load(MySQL5PlayerEventsWindowDAO.java]:40) ~[na:na]
        at com.aionemu.gameserver.services.player.PlayerService.getPlayer(PlayerService.java:210) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:316) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:290) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) ~[al-commons.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
18:29:51.132 ERROR[pool-2-thread-30]: - Could not restore f2p time for accountId: 2 from DB: Unknown column 'account_id' in 'where clause'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'account_id' in 'where clause'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_25]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5Free2PlayDAO.loadF2pInfo(MySQL5Free2PlayDAO.java]:52) ~[na:na]
        at com.aionemu.gameserver.services.player.PlayerService.getPlayer(PlayerService.java:213) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:316) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:290) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) ~[al-commons.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
18:29:51.184 WARN [pool-2-thread-30]: - Error executing select query com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_skill_skins' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_skill_skins' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_25]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at com.aionemu.commons.database.DB.select(DB.java:186) [al-commons.jar:na]
        at com.aionemu.commons.database.DB.select(DB.java:165) [al-commons.jar:na]
        at mysql5.MySQL5PlayerSkillSkinListDAO.loadSkillSkinList(MySQL5PlayerSkillSkinListDAO.java]:35) ~[na:na]
        at com.aionemu.gameserver.services.player.PlayerService.getPlayer(PlayerService.java:225) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:316) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:290) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) ~[al-commons.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
18:29:51.283 ERROR[pool-2-thread-30]: - Could not restore equipment setting for playerObjId: 321038 from DB: Table 'al_ser58_gs.player_equipment_setting' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_equipment_setting' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_25]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at mysql5.MySQL5PlayerEquipmentSettingDAO.loadEquipmentSetting(MySQL5PlayerEquipmentSettingDAO.java]:53) ~[na:na]
        at com.aionemu.gameserver.services.player.PlayerService.getPlayer(PlayerService.java:312) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:316) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:290) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) ~[al-commons.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
18:29:51.283 INFO [pool-2-thread-30]: - [MAC_AUDIT] Player Testname (account admint) has entered world with 90-2B-34-37-01-14 MAC.
18:29:51.294 INFO [pool-2-thread-30]: - [MonsterbookService] loaded ...
18:29:51.447 INFO [pool-2-thread-30]: - Player logged in: Testname Account: admint
18:29:51.454 INFO [pool-2-thread-30]: - Player Testname Received Ascension Boost
18:29:51.477 WARN [pool-2-thread-30]: - Error executing select query com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_events_window' doesn't exist
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'al_ser58_gs.player_events_window' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_25]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_25]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_25]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2030) ~[mysql-connector-java-5.1.33.jar:5.1.33]
        at com.jolbox.bonecp.PreparedStatementHandle.executeQuery(PreparedStatementHandle.java:172) ~[bonecp-0.7.1.RELEASE.jar:0.7.1.RELEASE]
        at com.aionemu.commons.database.DB.select(DB.java:186) [al-commons.jar:na]
        at com.aionemu.commons.database.DB.select(DB.java:165) [al-commons.jar:na]
        at mysql5.MySQL5PlayerEventsWindowDAO.getEventsWindow(MySQL5PlayerEventsWindowDAO.java]:115) ~[na:na]
        at com.aionemu.gameserver.services.EventWindowService.getPlayerEventsWindow(EventWindowService.java:103) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.EventWindowService.onLogin(EventWindowService.java:121) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService.enterWorld(PlayerEnterWorldService.java:601) ~[AL-Game.jar:na]
        at com.aionemu.gameserver.services.player.PlayerEnterWorldService$1.run(PlayerEnterWorldService.java:290) ~[AL-Game.jar:na]
        at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
        at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) ~[al-commons.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) ~[na:1.7.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:166) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) ~[na:1.7.0_25]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) ~[na:1.7.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ~[na:1.7.0_25]
        at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
18:29:51.481 INFO [pool-2-thread-30]: - Start counting id 1 time 60 minute(s)
18:29:51.483 INFO [pool-2-thread-30]: - Start counting id 2 time 60 minute(s)
18:29:51.483 INFO [pool-2-thread-30]: - Start counting id 3 time 60 minute(s)
18:29:51.484 INFO [pool-2-thread-30]: - Start counting id 4 time 30 minute(s)
18:29:51.485 INFO [ReadWrite-0 Dispatcher]: - event id 1 remain 60 start-time 1514877300 end-time 1564697700 total size 4
18:29:51.485 INFO [ReadWrite-0 Dispatcher]: - event id 2 remain 60 start-time 1514877300 end-time 1564697700 total size 4
18:29:51.486 INFO [ReadWrite-0 Dispatcher]: - event id 3 remain 60 start-time 1514877300 end-time 1564697700 total size 4
18:29:51.486 INFO [ReadWrite-0 Dispatcher]: - event id 4 remain 30 start-time 1528876800 end-time 1530691200 total size 4
18:29:51.521 INFO [pool-2-thread-30]: - Loading PetitionService ...
18:29:51.524 INFO [pool-2-thread-30]: - Successfully loaded 0 database petitions
18:29:51.534 INFO [pool-2-thread-30]: - [ConquerorsService] ==You're Last Activity [Testname]==
18:29:51.534 INFO [pool-2-thread-30]: - [ConquerorsService] Kills : 0
18:29:51.535 INFO [pool-2-thread-30]: - [ConquerorsService] Buffs Protector : 0
18:29:51.536 INFO [pool-2-thread-30]: - [ConquerorsService] Buffs Conqueror : 0
Daily: 20339
Daily: 30658
Daily: 30687
Daily: 30321
Daily: 31670
18:29:53.532 INFO [pool-2-thread-5]: - [SurveyController] update task start.
18:29:57.364 INFO [PacketProcessor:2]: - CraftSkillUpdateService: Initialized.

**Comment by Falke3434** [comment]
CHS Client is not supportet, we use only the Gameforge Client!
Use a new and clean DB - the Problem with the Skills come from a last update for the Skin Skills

**Comment by zxysm** [comment]
![3](https://user-images.githubusercontent.com/20953114/41499551-7e0ab3f4-71b4-11e8-8ac4-bcd42e4240ed.jpg)
Just tested with the Gameforge Client once, the same, it seems that the problem is not on the client.

**Comment by FrozenKiller35** [comment]
Could not restore Event Window account: 321038 from DB: Table 'al_ser58_gs.player_events_window' doesn't exist

;)

**Comment by zxysm** [comment]
Is there a solution? JAVA I do not understand.

**Comment by FrozenKiller35** [comment]
https://www.xup.in/dl,11625242/al_server_gs.rar/ Full and Clean DB (All updates Included)

**Comment by zxysm** [comment]
I will try it, thank you very much!

**Comment by zxysm** [comment]
@FrozenKiller35 Thanks again, importing new SQL and fixing it is working!

**Comment by zxysm** [comment]
![2018-06-16_233445](https://user-images.githubusercontent.com/20953114/41500117-d7e7afc6-71be-11e8-9684-397d37e05fdb.jpg)
![2018-06-16_233933](https://user-images.githubusercontent.com/20953114/41500118-d822a982-71be-11e8-9086-5b2733f598b2.jpg)
In addition, the test does not only work on the Gameforge client. The CHS client can also work properly with minor modifications.
