### ISSUE TITLE
"Adma Stronghold Treasure Chest" item problem

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#65]
If i added this item to inventory and try to open: "Adma Stronghold Treasure Chest" = player disconnected.
Character is unplayable if You try to relogin with this char.
I checked what item exactly does the problem:

item_template id="182007394" name="Damaged Necklace"

Probably slot is missing in "item_templates" file.

2018-06-17 12:09:29,290 Dispatcher error! java.lang.IllegalArgumentException: Invalid provided slotIdMask 0
java.lang.IllegalArgumentException: Invalid provided slotIdMask 0
	at com.aionemu.gameserver.model.items.ItemSlot.getSlotFor(ItemSlot.java:149) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.iteminfo.ArmorInfoBlobEntry.writeThisBlob(ArmorInfoBlobEntry.java:41) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.iteminfo.ItemBlobEntry.writeMe(ItemBlobEntry.java:53) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.iteminfo.ItemInfoBlob.writeMe(ItemInfoBlob.java:53) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.serverpackets.SM_INVENTORY_INFO.writeItemInfo(SM_INVENTORY_INFO.java:73) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.serverpackets.SM_INVENTORY_INFO.writeImpl(SM_INVENTORY_INFO.java:61) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionServerPacket.write(AionServerPacket.java:144) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.network.aion.AionConnection.writeData(AionConnection.java:321) ~[AL-Game.jar:na]

**Comment by Falke3434** [comment]
fixed

**Comment by benas80** [comment]
thanks
