### ISSUE TITLE
Siege Boss not found for siege - Null Pointer

### ISSUE THREAD

**Issue by benas80** [AionGermany/aion-germany#69]
018-06-20 21:00:00,066 Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1241
	at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:221) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:104) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:82) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:247) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:230) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.siegeservice.SiegeStartRunnable.run(SiegeStartRunnable.java:34) ~[AL-Game.jar:na]
	at com.aionemu.commons.utils.concurrent.ExecuteWrapper.execute(ExecuteWrapper.java:48) ~[al-commons.jar:na]
	at com.aionemu.commons.utils.concurrent.RunnableWrapper.run(RunnableWrapper.java:40) [al-commons.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
	at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]

----------------------
Two other bugs same as upper :

2018-06-20 21:00:00,142 Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1231

2018-06-20 21:00:00,144 Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1221

**Comment by FrozenKiller35** [comment]
Cant confirm this 😮

**Comment by benas80** [comment]
I just let the server run, this problems showed on the GS console.

**Comment by FrozenKiller35** [comment]
maybe ;)

**Comment by benas80** [comment]
I run game server for testing and now (time: 18:00) again these bugs showes.
 (but not the same numbers)
-Siege Boss not found for siege 1132
-Siege Boss not found for siege 1131
-Siege Boss not found for siege 1141

**Comment by benas80** [comment]
Ok, i found problem i think.
I have in this directory backup rar of this reshanta spawn. I remove it from here and there is no bugs on the console.

**Comment by benas80** [comment]
Problem occured again but only for siege 1011 (Divine Fortress)

2018-06-26 21:00:00,095 Exception in a Runnable execution:
com.aionemu.gameserver.services.siegeservice.SiegeException: [SiegeService] Siege Boss not found for siege 1011
	at com.aionemu.gameserver.services.siegeservice.Siege.initSiegeBoss(Siege.java:223) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.siegeservice.FortressSiege.onSiegeStart(FortressSiege.java:104) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.siegeservice.Siege.startSiege(Siege.java:82) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.SiegeService.startSiege(SiegeService.java:247) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.services.SiegeService.checkSiegeStart(SiegeService.java:230) ~[AL-Game.jar:na]

**Comment by FrozenKiller35** [comment]
Thx i will check it when i have some time
