### ISSUE TITLE
Fixed some EventWindow Bugs

### ISSUE THREAD

**Issue by FrozenKiller35** [AionGermany/aion-germany#70]
TODO:

Better shedule ....
Remove recived reward from displayed list

Pls report Bugs for EventWindow here.

**Comment by weixiao0412** [comment]
2018-06-21 10:25:53,022 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 81
Column: 1
2018-06-21 10:25:53,024 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 81
Column: 4
2018-06-21 10:25:53,025 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 81
Column: 7
2018-06-21 10:25:53,026 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 82
Column: 1
2018-06-21 10:25:53,028 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 82
Column: 4
2018-06-21 10:25:53,029 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 82
Column: 7
2018-06-21 10:25:53,030 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 82
Column: 10
2018-06-21 10:25:53,031 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 83
Column: 1
2018-06-21 10:25:53,032 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 83
Column: 4
2018-06-21 10:25:53,034 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 83
Column: 7
2018-06-21 10:25:53,034 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 83
Column: 10
2018-06-21 10:25:53,037 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 83
Column: 30
2018-06-21 10:25:53,038 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 84
Column: 1
2018-06-21 10:25:53,039 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 84
Column: 4
2018-06-21 10:25:53,040 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 84
Column: 7
2018-06-21 10:25:53,043 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 84
Column: 10
2018-06-21 10:25:53,045 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 84
Column: 17
2018-06-21 10:25:53,046 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 85
Column: 1
2018-06-21 10:25:53,047 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 85
Column: 4
2018-06-21 10:25:53,050 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 85
Column: 7
2018-06-21 10:25:53,051 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 85
Column: 10
2018-06-21 10:25:53,052 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 85
Column: 17
2018-06-21 10:25:53,053 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 86
Column: 1
2018-06-21 10:25:53,058 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 86
Column: 4
2018-06-21 10:25:53,059 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 86
Column: 7
2018-06-21 10:25:53,061 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 86
Column: 10
2018-06-21 10:25:53,062 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 86
Column: 17
2018-06-21 10:25:53,063 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 87
Column: 1
2018-06-21 10:25:53,064 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 87
Column: 4
2018-06-21 10:25:53,065 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 87
Column: 7
2018-06-21 10:25:53,066 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 87
Column: 10
2018-06-21 10:25:53,067 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 87
Column: 17
2018-06-21 10:25:53,068 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 88
Column: 1
2018-06-21 10:25:53,069 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 88
Column: 4
2018-06-21 10:25:53,070 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 88
Column: 7
2018-06-21 10:25:53,071 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 88
Column: 10
2018-06-21 10:25:53,072 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 88
Column: 17
2018-06-21 10:25:53,073 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 89
Column: 1
2018-06-21 10:25:53,074 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 89
Column: 4
2018-06-21 10:25:53,075 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 89
Column: 7
2018-06-21 10:25:53,076 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 90
Column: 1
2018-06-21 10:25:53,076 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 90
Column: 4
2018-06-21 10:25:53,077 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 90
Column: 7
2018-06-21 10:25:53,078 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 90
Column: 10
2018-06-21 10:25:53,079 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 90
Column: 16
2018-06-21 10:25:53,080 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 91
Column: 1
2018-06-21 10:25:53,081 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 91
Column: 4
2018-06-21 10:25:53,081 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 91
Column: 7
2018-06-21 10:25:53,082 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 92
Column: 1
2018-06-21 10:25:53,082 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 92
Column: 4
2018-06-21 10:25:53,083 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 92
Column: 7
2018-06-21 10:25:53,084 Java Compiler ERROR: "finally" Without "try"
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 92
Column: 9
2018-06-21 10:25:53,084 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 93
Column: 1
2018-06-21 10:25:53,085 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 93
Column: 4
2018-06-21 10:25:53,086 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 93
Column: 7
2018-06-21 10:25:53,087 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 93
Column: 10
2018-06-21 10:25:53,087 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 93
Column: 28
2018-06-21 10:25:53,088 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 94
Column: 1
2018-06-21 10:25:53,089 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 94
Column: 4
2018-06-21 10:25:53,090 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 94
Column: 7
2018-06-21 10:25:53,091 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 111
Column: 1
2018-06-21 10:25:53,092 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 111
Column: 4
2018-06-21 10:25:53,093 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 111
Column: 7
2018-06-21 10:25:53,094 Java Compiler ERROR: Illegal type started
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 112
Column: 1
2018-06-21 10:25:53,095 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 112
Column: 4
2018-06-21 10:25:53,096 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 112
Column: 7
2018-06-21 10:25:53,096 Java Compiler ERROR: need <Identifier>
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 112
Column: 9
2018-06-21 10:25:53,097 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 112
Column: 14
2018-06-21 10:25:53,098 Java Compiler ERROR: Illegal type started
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 113
Column: 1
2018-06-21 10:25:53,099 Java Compiler ERROR: need <Identifier>
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 113
Column: 4
2018-06-21 10:25:53,099 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 113
Column: 7
2018-06-21 10:25:53,100 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 114
Column: 1
2018-06-21 10:25:53,101 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 114
Column: 4
2018-06-21 10:25:53,102 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 114
Column: 7
2018-06-21 10:25:53,102 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 115
Column: 1
2018-06-21 10:25:53,103 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 115
Column: 4
2018-06-21 10:25:53,103 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 115
Column: 7
2018-06-21 10:25:53,104 Java Compiler ERROR: Illegal type started
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 116
Column: 1
2018-06-21 10:25:53,104 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 116
Column: 4
2018-06-21 10:25:53,105 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 116
Column: 7
2018-06-21 10:25:53,105 Java Compiler ERROR: need <Identifier>
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 116
Column: 9
2018-06-21 10:25:53,106 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 116
Column: 14
2018-06-21 10:25:53,107 Java Compiler ERROR: Illegal type started
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 117
Column: 1
2018-06-21 10:25:53,107 Java Compiler ERROR: need <Identifier>
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 117
Column: 4
2018-06-21 10:25:53,108 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 117
Column: 7
2018-06-21 10:25:53,109 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 118
Column: 1
2018-06-21 10:25:53,110 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 118
Column: 4
2018-06-21 10:25:53,110 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 118
Column: 7
2018-06-21 10:25:53,111 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 119
Column: 1
2018-06-21 10:25:53,112 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 119
Column: 4
2018-06-21 10:25:53,113 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 119
Column: 7
2018-06-21 10:25:53,114 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 120
Column: 1
2018-06-21 10:25:53,115 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 120
Column: 4
2018-06-21 10:25:53,115 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 120
Column: 7
2018-06-21 10:25:53,116 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 121
Column: 1
2018-06-21 10:25:53,116 Java Compiler ERROR: Illegal expression starts
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 121
Column: 4
2018-06-21 10:25:53,117 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 121
Column: 7
2018-06-21 10:25:53,117 Java Compiler ERROR: Illegal type started
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 122
Column: 1
2018-06-21 10:25:53,118 Java Compiler ERROR: need ';'
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 122
Column: 4
2018-06-21 10:25:53,118 Java Compiler ERROR: Floating-point literals are irregular
Source: /E:/AL-5.8/AL-Game/./data/scripts/system/database/mysql5/MySQL5PlayerEventsWindowDAO.java
Line: 122
Column: 7
2018-06-21 10:25:53,150 Critical Error - Thread: main terminated abnormaly: java.lang.Error: Error while compiling classes
java.lang.Error: Error while compiling classes
	at com.aionemu.commons.database.dao.DAOManager.init(DAOManager.java:75) ~[al-commons.jar:na]
	at com.aionemu.gameserver.GameServer.initUtilityServicesAndConfig(GameServer.java:513) ~[AL-Game.jar:na]
	at com.aionemu.gameserver.GameServer.main(GameServer.java:239) ~[AL-Game.jar:na]
Caused by: java.lang.RuntimeException: Error while compiling classes
	at com.aionemu.commons.scripting.impl.javacompiler.ScriptCompilerImpl.doCompilation(ScriptCompilerImpl.java:196) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.impl.javacompiler.ScriptCompilerImpl.compile(ScriptCompilerImpl.java:165) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.impl.ScriptContextImpl.init(ScriptContextImpl.java:143) ~[al-commons.jar:na]
	at com.aionemu.commons.scripting.scriptmanager.ScriptManager.load(ScriptManager.java:97) ~[al-commons.jar:na]
	at com.aionemu.commons.database.dao.DAOManager.init(DAOManager.java:72) ~[al-commons.jar:na]

**Comment by FrozenKiller35** [comment]
Ups sry i already know where this come from
 i can fix it after work :O
